### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by jack-ew** [RWTH-EBC/TEASER#296] opened 2016-08-10 09:17 UTC
If you import teaser with:
`from teaser.project import Project`

you get the error about write permissions:
`[Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/teaser/OutputData'`

In linux you don't have this write permissions for your normal Systempath. I think the simplest solution would be a function that asks for a different path

**Comment by pema1** [comment] 2016-08-18 11:56
Having an output directory inside the package structure is not really nice. Perhaps Python can be made using the user's home directory for outputs as a default. That should work on any platform, hopefully.

@jack-ew maybe you can use a _virtualenv_ in your home path to install and use teaser for the time being.

**Comment by PRemmen** [comment] 2016-09-21 08:52
@MichaMans is this ready to merge for new release (see other 4 bug pull requests)

**Comment by MichaMans** [comment] 2016-09-21 09:25
I haven't tested it yet, so i would suggest to test it first. The problem is, since this is a pip related error we need to install this branch with pip and then test the functionality. Do you have any suggestions how to do so?

**Comment by PRemmen** [comment] 2016-09-23 09:46
@jack-ew we solved this issue with latest version (v0.3.9) can you verify that?

**Comment by PRemmen** [comment] 2016-09-26 08:42
closed by #311

**Closed by PRemmen** 2016-09-26 08:42 UTC
Labels: bug
