### ISSUE TITLE
net_leased_area

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#499] opened 2017-12-11 13:47 UTC
## What is the problem?

- In building.py set_gml_attributes is net_leased_area = gross floor area (in German: Bruttogrundfläche) (see picture)! Because get_footprint_gml () returns the gross floor area of the floor plate. Right?
![3](https://user-images.githubusercontent.com/19650702/33833755-f136fba2-de80-11e7-8f35-d14b4cd516e6.PNG)

From the term 'net_leased_area' and also according to the formulas in TEASER with 'self. area' = 'net_leased_area', e. g. in set_volume_zone (see below), the parameter 'net_leased_area' should mean the net floor area (in German: Nettogrundfläche).
![2](https://user-images.githubusercontent.com/19650702/33833905-7a9b9664-de81-11e7-830a-c3300af1005a.PNG)

## Why do we want to solve it?

Different use of the parameter confuses TEASER users.

## How do we want to solve it?

Clear definitions in a more detailed documentation than http://pythonhosted.org/teaser/py-modindex.html would be optimal.

**Comment by PRemmen** [comment] 2017-12-11 14:43
@RWTHSebastian Great you found that ambiguity! :) 

I think you already described the solution.

Just one comment: the problem is in the calculation of the net area from CityGML data. Here we needed to make some assumptions, because net area is not described in CityGML. So I would to suggest to cleary explain this in the docstring.

I'm looking forward to an implemented solution.

**Comment by PRemmen** [comment] 2020-01-16 15:51
as we no longer support gml, close it

**Closed by PRemmen** 2020-01-16 15:51 UTC
