### ISSUE TITLE
Problem simulating basic TEASER example in Ubuntu 16.04.4 installed in Oracle VM VirtualBox

### ISSUE THREAD

**Issue by filokot** [RWTH-EBC/TEASER#517] opened 2018-06-05 06:35 UTC
Hi all,

I did the following:

1. Used /TEASER-master/teaser/examples/e2_export_aixlib_models.py in Ubuntu (installed in Oracle VBox) to generate /TEASEROutput/ArchetypeExample/

2. Loaded AixLib to Dymola and opened ArchetypeExample/package.mo 

3. Simulated either ResidentialBuilding, OfficeBuilding or InstituteBuilding. 

**Problem**: compilation fails giving the message below in the simulation window. 

**Note**: This problem does not occur in Windows 10: I have ran the same models with no problem by changing the weather file path from "/home/konstantinfilonenko/.local/lib/python3.5/site-packages/teaser/data/input/inputdata/weatherdata/DEU_BW_Mannheim_107290_TRY2010_12_Jahr_BBSR.mos" to "C:/TEASER/teaser/data/input/inputdata/weatherdata/DEU_BW_Mannheim_107290_TRY2010_12_Jahr_BBSR.mos"

**Error message:**

/opt/dymola-2017-x86_64/source/matrixop.c: In function ‘Integer2String’:

/opt/dymola-2017-x86_64/source/matrixop.c:3579:14: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘int’ [-Wformat=]

sprintf(buf,"%*.*ld",(int)minwidth,(int)precision,(int)x);

^

/opt/dymola-2017-x86_64/source/matrixop.c: In function ‘Integer2String2’:

/opt/dymola-2017-x86_64/source/matrixop.c:3600:28: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]

sprintf(buf,leftJustified?"%-*ld":"%*ld",(int)minwidth,(int)x);

^

/opt/dymola-2017-x86_64/source/matrixop.c:3600:36: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]

sprintf(buf,leftJustified?"%-*ld":"%*ld",(int)minwidth,(int)x);

^

In file included from /opt/dymola-2017-x86_64/source/matrixop.c:3746:0:

/opt/dymola-2017-x86_64/source/localeless.cpp: In function ‘sscanfCx2_underscore’:

/opt/dymola-2017-x86_64/source/localeless.cpp:315:22: warning: format ‘%lx’ expects argument of type ‘long unsigned int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]

return sscanf(line, "%lx_%lx", a,b);

^

/opt/dymola-2017-x86_64/source/localeless.cpp:315:22: warning: format ‘%lx’ expects argument of type ‘long unsigned int *’, but argument 4 has type ‘unsigned int *’ [-Wformat=]

/opt/dymola-2017-x86_64/source/localeless.cpp: In function ‘sscanfClu’:

/opt/dymola-2017-x86_64/source/localeless.cpp:326:22: warning: format ‘%lu’ expects argument of type ‘long unsigned int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]

return sscanf(line, "%lu", a);

^

/usr/bin/ld: cannot find -lLapack

/tmp/cc0nDfaG.o: In function `ModelicaInternal_temporaryFileName':

dsmodel.c:(.text+0x7599): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

/opt/dymola-2017-x86_64/Modelica/Library/Modelica 3.2.2/Resources/Library/linux32/libModelicaMatIO.a(ModelicaMatIO.o): In function `Mat_VarDelete':

ModelicaMatIO.c:(.text+0x3b7d0): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'

collect2: error: ld returned 1 exit status

Konstantin

**Comment by mlauster** [comment] 2018-06-05 06:58
@filokot, it hard to tell from that distance what the exact problem is that you encounter. But given the error message, it looks like some Dymola functions handling names cannot encode the file names on Ubuntu. I propose to first check your Dymola and Compiler installation (by using compiler check in Dymola) and then try some examples in Dymola. If this works fine, try to change the name of the file generated by TEASER to something very basic without number or underscores.

**Comment by MichaMans** [comment] 2018-06-05 15:53
@filokot i tried to reproduce this error but i failed installing und using VirtualBox. So i tested it again under ubuntu 16.04 with dymola in your reported way. I could simulate this without an error. Could you check if the example of the AixLib itself are simulating or other models are working?

**Comment by filokot** [comment] 2018-06-05 21:14
@mlauster and @MichaMans, thank you for help and time, seems that the issue has nothing to do with the TEASER.

To my surprise, **Compiler tab** in **Simulation -> Setup** is not accessible. Not sure how to switch it on, so I will just reinstall Modelica. Additionally, I have run the model with different compilers (default for the model was Radau IIa) and it clearly worked only with Dassl and Euler, most other give the same error. I tried my own models with different solvers, for which I usually use Dassl, and there is the same issue.

**Comment by MichaMans** [comment] 2018-06-06 06:51
@filokot Ok perfect! We noticed some issues with the solvers as well. We should switch to cvode or dassl as default solver. We already did this in the development. A release will be done in the near future. Could you close this again if you think this is done/solved?

**Closed** 2018-06-06 10:39 UTC
